export PORT := "/dev/ttyACM0"

watch:
    watchexec -e py just run

run: upload
    rshell -p $PORT --buffer-size 512 'repl ~ import sys ~ sys.exit() ~'

serial:
    minicom -o -D $PORT

shell:
    rshell -p $PORT --buffer-size 512

upload:
    rshell -p $PORT --buffer-size 512 cp *.py /pyboard/
